### ISSUE TITLE
Webp support?

### ISSUE THREAD

**Issue by josephrocca** [pwlmaciejewski/imghash#3]
Webp images are starting to become quite common now that they're supported in chrome (encoding and decoding), firefox (decoding only), etc. Is there any interest in supporting hashing of webp images?

**Comment by pwlmaciejewski** [comment]
@josephrocca yes, it should be fairly easy if there's already a webp lib that can decode the file. Do you know any?

**Comment by LinusU** [comment]
@josephrocca @pwlmaciejewski I've released some packages which should allow you to efficiently decode most image formats:

- https://www.npmjs.com/package/@cwasm/jpeg-turbo
- https://www.npmjs.com/package/@cwasm/lodepng
- https://www.npmjs.com/package/@cwasm/nsbmp
- https://www.npmjs.com/package/@cwasm/nsgif
- https://www.npmjs.com/package/@cwasm/webp

I've also released a high level `Image` implementation for Node.js which can read any image using the above implementations for you.

- https://www.npmjs.com/package/@canvas/image

**Comment by LinusU** [comment]
Submitted a PR to use `@canvas/image` here ☺️ #16
