### ISSUE TITLE
Two different pictures, with the same hash? 

### ISSUE THREAD

**Issue by snoopy83101** [pwlmaciejewski/imghash#46]
http://file.geeknt.com/upload/20200612/4a5a7f5c-5417-4c53-bf1c-23dcf2b12c24.jpg
http://file.geeknt.com/upload/20200612/3512a09d-4f81-4518-9391-a253e631657f.jpg

 imghash
      .hash(o.path, 4, "binary")
      .then((hash) => {
        resolve(hash);  //1100110011001100
      })
      .catch((e) => {
        reject(e);
      });

why?  

I want to make them unique, and when generating a hash, don't take up too much system resources, how can I do it?

**Comment by pwlmaciejewski** [comment]
Hi @snoopy83101 

Increasing "bits" parameter you should do the trick. Please try this:

```js
imghash
  .hash(o.path, 8, "binary")
  .then((hash) => {
    resolve(hash);
  })
  .catch((e) => {
    reject(e);
  });
```

It will return a longer hash with a higher resolution. Hashes for the two images should no longer be the same either.

**Comment by snoopy83101** [comment]
@pwlmaciejewski 
Thanks for the reply, if the length is 8, the two pictures are indeed returned differently.
But if I have ten thousand pictures, does he still have the same probability?

**Comment by pwlmaciejewski** [comment]
@snoopy83101 It depends heavily on the similarity of the pictures. If not having collisions is your priority then use a very high bit length, eg. `256` and more. Collisions are still possible since you can never rule them out, but with long hashes, you should be relatively safe.

**Comment by snoopy83101** [comment]
> @snoopy83101 It depends heavily on the similarity of the pictures. If not having collisions is your priority then use a very high bit length, eg. `256` and more. Collisions are still possible since you can never rule them out, but with long hashes, you should be relatively safe.

@pwlmaciejewski hi, I also want to ask about the probability of repetition


imghash.hash(o.path, 12, "binary")：
111111100011111110000000111100000000101110010000011100000111111010000111100000000110100111111110100111000110110010000111011000000111111000001111

imghash.hash(o.path)：
f884c4d8d1193c07

Which one has the greater probability of repetition?

Which one will consume more system resources?
